services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev-stage
    container_name: vinom_session_manager
    volumes:
      - .:/app
      - /app/tmp
    environment:
      Host_IP: app
      PROXY_IP: ${PROXY_IP} 
      UDP_PORT: ${UDP_PORT}
      UDP_BUFFER_SIZE: ${UDP_BUFFER_SIZE}
      GRPC_PORT: ${GRPC_PORT}
